[2024-10-27T16:52:11.323+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-27T16:52:11.348+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag2.second_task manual__2024-10-27T16:52:07.189790+00:00 [queued]>
[2024-10-27T16:52:11.360+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag2.second_task manual__2024-10-27T16:52:07.189790+00:00 [queued]>
[2024-10-27T16:52:11.361+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-10-27T16:52:11.389+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): second_task> on 2024-10-27 16:52:07.189790+00:00
[2024-10-27T16:52:11.397+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag2', 'second_task', 'manual__2024-10-27T16:52:07.189790+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp95e1t_1k']
[2024-10-27T16:52:11.399+0000] {standard_task_runner.py:105} INFO - Job 64: Subtask second_task
[2024-10-27T16:52:11.402+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=234) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-27T16:52:11.403+0000] {standard_task_runner.py:72} INFO - Started process 235 to run task
[2024-10-27T16:52:11.479+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag2.second_task manual__2024-10-27T16:52:07.189790+00:00 [running]> on host 2d730dc1e71d
[2024-10-27T16:52:11.575+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='johnwell' AIRFLOW_CTX_DAG_ID='our_first_dag2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T16:52:07.189790+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-27T16:52:07.189790+00:00'
[2024-10-27T16:52:11.578+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-27T16:52:11.596+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-27T16:52:11.597+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am the second task after task 1']
[2024-10-27T16:52:11.607+0000] {subprocess.py:86} INFO - Output:
[2024-10-27T16:52:11.609+0000] {subprocess.py:93} INFO - hey, I am the second task after task 1
[2024-10-27T16:52:11.610+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-27T16:52:11.648+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-27T16:52:11.649+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag2, task_id=second_task, run_id=manual__2024-10-27T16:52:07.189790+00:00, execution_date=20241027T165207, start_date=20241027T165211, end_date=20241027T165211
[2024-10-27T16:52:11.703+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-27T16:52:11.725+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-27T16:52:11.744+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
