[2024-11-02T07:19:00.767+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T07:19:00.785+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_V1.get_name manual__2024-11-02T07:18:59.454164+00:00 [queued]>
[2024-11-02T07:19:00.794+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_V1.get_name manual__2024-11-02T07:18:59.454164+00:00 [queued]>
[2024-11-02T07:19:00.794+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-02T07:19:00.815+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_name> on 2024-11-02 07:18:59.454164+00:00
[2024-11-02T07:19:00.827+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2226) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-02T07:19:00.831+0000] {standard_task_runner.py:72} INFO - Started process 2227 to run task
[2024-11-02T07:19:00.830+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_V1', 'get_name', 'manual__2024-11-02T07:18:59.454164+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python.py', '--cfg-path', '/tmp/tmpop29n4uf']
[2024-11-02T07:19:00.836+0000] {standard_task_runner.py:105} INFO - Job 129: Subtask get_name
[2024-11-02T07:19:00.886+0000] {task_command.py:467} INFO - Running <TaskInstance: our_dag_with_python_operator_V1.get_name manual__2024-11-02T07:18:59.454164+00:00 [running]> on host 2d730dc1e71d
[2024-11-02T07:19:01.046+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='johnwell' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_V1' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T07:18:59.454164+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T07:18:59.454164+00:00'
[2024-11-02T07:19:01.047+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T07:19:01.069+0000] {python.py:240} INFO - Done. Returned value was: Jerry
[2024-11-02T07:19:01.097+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T07:19:01.098+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_V1, task_id=get_name, run_id=manual__2024-11-02T07:18:59.454164+00:00, execution_date=20241102T071859, start_date=20241102T071900, end_date=20241102T071901
[2024-11-02T07:19:01.131+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T07:19:01.157+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-02T07:19:01.163+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
