[2024-10-27T17:06:52.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-27T17:06:52.445+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.second_task manual__2024-10-27T17:06:51.042508+00:00 [queued]>
[2024-10-27T17:06:52.456+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.second_task manual__2024-10-27T17:06:51.042508+00:00 [queued]>
[2024-10-27T17:06:52.457+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-10-27T17:06:52.480+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): second_task> on 2024-10-27 17:06:51.042508+00:00
[2024-10-27T17:06:52.487+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'second_task', 'manual__2024-10-27T17:06:51.042508+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpjhtx72ll']
[2024-10-27T17:06:52.489+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask second_task
[2024-10-27T17:06:52.492+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=694) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-27T17:06:52.492+0000] {standard_task_runner.py:72} INFO - Started process 695 to run task
[2024-10-27T17:06:52.534+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v3.second_task manual__2024-10-27T17:06:51.042508+00:00 [running]> on host 2d730dc1e71d
[2024-10-27T17:06:52.607+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='johnwell' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-27T17:06:51.042508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-27T17:06:51.042508+00:00'
[2024-10-27T17:06:52.608+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-27T17:06:52.622+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-27T17:06:52.622+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am the second task after task 1']
[2024-10-27T17:06:52.630+0000] {subprocess.py:86} INFO - Output:
[2024-10-27T17:06:52.631+0000] {subprocess.py:93} INFO - hey, I am the second task after task 1
[2024-10-27T17:06:52.632+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-27T17:06:52.669+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-27T17:06:52.670+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=second_task, run_id=manual__2024-10-27T17:06:51.042508+00:00, execution_date=20241027T170651, start_date=20241027T170652, end_date=20241027T170652
[2024-10-27T17:06:52.709+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-27T17:06:52.721+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-27T17:06:52.728+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
